version: '3.8'
services:
  auth-service:
    build: ./Backend/auth-service
    ports: 
      - 8080:3001
    volumes:
      - auth-data:/app/data
      - auth-logs:/app/logs

  media-service:
    build: ./Backend/media-service
    ports:
       - 8081:3002
    volumes:
      - media-data:/app/media


  post-service:
    build: ./Backend/post-service
    ports:
      - 8082:3003
    volumes:
      - post-data:/app/post 




  user-service:
    build: ./Backend/user-service
    ports: 
       - 8083:3004    
    volumes:
      - user-data:/app/user    

volumes:
  auth-data:
  auth-logs:
  post-data:
  media-data:
  user-data:       