services:
  - name: auth-service
    image: tanishakum/auth-service:latest
    port: 3001
    nodePort: 30080

  - name: media-service
    image: tanishakum/media-service:latest
    port: 3002
    nodePort: 30081

  - name: post-service
    image: tanishakum/post-service:latest   # ✅ fixed
    port: 3003
    nodePort: 30082

  - name: user-service
    image: tanishakum/user-service:latest
    port: 3004
    nodePort: 30083