name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Show Files
        run: ls -la

      - name: Build Containers
        run: docker compose build

      - name: Start Containers
        run: docker compose up -d

      - name: Show Running Containers
        run: docker ps

      - name: Stop Containers
        run: docker compose down