#FROM node:18-alpine
#WORKDIR /app
#COPY package*.json ./
#RUN npm install
#COPY . .
#CMD ["npm", "start"] 

FROM node:18-alpine AS Builder
WORKDIR /app
COPY package*.json ./
RUN npm ci --only=production

FROM node:18-alpine
WORKDIR /app
COPY --from=Builder /app/package*.json ./
COPY --from=Builder /app/node_modules ./node_modules
COPY . .
CMD ["npm", "start"]