name: CI Pipeline

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build-test-run:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout Source Code
      - name: Checkout Code
        uses: actions/checkout@v4

      # 2. Show Files
      - name: Show Project Files
        run: ls -la

      # 3. Check Docker Installed
      - name: Check Docker Version
        run: |
          docker --version
          docker compose version

      # 4. Build All Containers
      - name: Build Docker Images
        run: docker compose build

      # 5. Start All Services
      - name: Start Containers
        run: docker compose up -d

      # 6. Wait for Containers to Boot
      - name: Wait for Services
        run: sleep 20

      # 7. Show Running Containers
      - name: Check Running Containers
        run: docker ps

      # 8. Show Logs (for debugging)
      - name: Show Container Logs
        run: docker compose logs

      # 9. Health Check Example (change port if needed)
      - name: Health Check Application
        run: |
          curl -f http://localhost:8080/login || exit 1

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Auth Image
        run: docker push tanishakum/auth-service

      - name: Push Media Image
        run: docker push tanishakum/media-service

      - name: Push Post Image
        run: docker push tanishakum/post-service

      - name: Push User Image
        run: docker push tanishakum/user-service
    

      # 10. Cleanup Always
      - name: Stop Containers
        run: docker compose down
        if: always()